using System.Collections.Generic;

namespace BlueDental.RolePermission;

internal static class PermissionTreeBuilder
{
    public static List<PermissionTreeNode> Build() =>
    [
        Group("patient", "Khách hàng",
            Leaf("patient.read", "Xem"),
            Leaf("patient.create", "Thêm"),
            Leaf("patient.update", "Sửa"),
            Leaf("patient.hidePhone", "Ẩn số điện thoại"),
            Leaf("patient.export", "Xuất dữ liệu"),
            Group("payment", "Thanh toán",
                Leaf("payment.read", "Xem"),
                Leaf("payment.create", "Thêm"),
                Leaf("payment.update", "Sửa"),
                Leaf("payment.delete", "Xoá"),
                Leaf("payment.export", "Xuất dữ liệu"),
                Leaf("payment.finalize", "Chốt phiếu"))),

        Group("treatment-group", "Điều trị",
            Group("treatmentDiagnosis", "Phiếu chẩn đoán",
                Leaf("treatmentDiagnosis.read", "Xem"),
                Leaf("treatmentDiagnosis.create", "Thêm"),
                Leaf("treatmentDiagnosis.update", "Sửa"),
                Leaf("treatmentDiagnosis.delete", "Xoá")),
            Group("treatmentConsultation", "Phiếu tư vấn",
                Leaf("treatmentConsultation.read", "Xem"),
                Leaf("treatmentConsultation.create", "Thêm"),
                Leaf("treatmentConsultation.update", "Sửa"),
                Leaf("treatmentConsultation.delete", "Xoá"),
                Leaf("treatmentConsultation.print", "In chẩn đoán")),
            Group("treatmentStage", "Công đoạn",
                Leaf("treatmentStage.read", "Xem"),
                Leaf("treatmentStage.create", "Thêm"),
                Leaf("treatmentStage.update", "Sửa"),
                Leaf("treatmentStage.continue", "Tiếp tục công đoạn"),
                Leaf("treatmentStage.complete", "Hoàn thành công đoạn"),
                Leaf("treatmentStage.print", "In công đoạn")),
            Group("appointment-in-treatment", "Lịch hẹn",
                Leaf("appointment.read", "Xem"),
                Leaf("appointment.create", "Thêm"),
                Leaf("appointment.update", "Sửa"),
                Leaf("appointment.delete", "Xoá"),
                Leaf("appointment.export", "Xuất dữ liệu")),
            Group("treatmentImage", "Hình ảnh",
                Leaf("treatmentImage.read", "Xem"),
                Leaf("treatmentImage.create", "Thêm"),
                Leaf("treatmentImage.update", "Sửa"),
                Leaf("treatmentImage.delete", "Xoá"),
                Leaf("treatmentImage.export", "Xuất dữ liệu")),
            Group("patientMedicalRecord", "Bệnh án",
                Leaf("patientMedicalRecord.read", "Xem"),
                Leaf("patientMedicalRecord.create", "Thêm"),
                Leaf("patientMedicalRecord.update", "Sửa"),
                Leaf("patientMedicalRecord.delete", "Xoá"),
                Leaf("patientMedicalRecord.print", "In biểu mẫu")),
            Group("treatmentLabo", "Labo",
                Leaf("treatmentLabo.read", "Xem"),
                Leaf("treatmentLabo.create", "Thêm"),
                Leaf("treatmentLabo.update", "Sửa"),
                Leaf("treatmentLabo.delete", "Xoá"),
                Leaf("treatmentLabo.export", "Xuất dữ liệu")),
            Group("prescription", "Đơn thuốc",
                Leaf("prescription.read", "Xem"),
                Leaf("prescription.create", "Thêm"),
                Leaf("prescription.update", "Sửa"),
                Leaf("prescription.delete", "Xoá"),
                Leaf("prescription.export", "Xuất dữ liệu")),
            Group("treatmentCskh", "CSKH",
                Leaf("treatmentCskh.read", "Xem"),
                Leaf("treatmentCskh.create", "Thêm"),
                Leaf("treatmentCskh.update", "Sửa"),
                Leaf("treatmentCskh.delete", "Xoá"),
                Leaf("treatmentCskh.export", "Xuất dữ liệu"))),

        Group("appointment-standalone", "Lịch hẹn",
            Group("appointment", "Lịch hẹn khách hàng",
                Leaf("appointment.read", "Xem"),
                Leaf("appointment.create", "Thêm"),
                Leaf("appointment.update", "Sửa"),
                Leaf("appointment.delete", "Xoá"),
                Leaf("appointment.export", "Xuất dữ liệu")),
            Group("workSchedule", "Lịch làm việc",
                Leaf("workSchedule.read", "Xem"),
                Leaf("workSchedule.update", "Sửa"),
                Leaf("workSchedule.attendanceOthers", "Điểm danh NV khác"))),

        Group("reception", "Tiếp nhận",
            Leaf("reception.read", "Xem"),
            Leaf("reception.create", "Thêm"),
            Leaf("reception.update", "Sửa"),
            Leaf("reception.delete", "Xoá"),
            Leaf("reception.export", "Xuất dữ liệu")),

        Group("operations-group", "Quản trị vận hành",
            Group("operations-overview", "Quản trị vận hành",
                Group("operationsOverviewHome", "Trang chủ",
                    Leaf("operationsOverviewHome.read", "Xem"),
                    Leaf("operationsOverviewHome.create", "Thêm"),
                    Leaf("operationsOverviewHome.update", "Sửa"),
                    Leaf("operationsOverviewHome.delete", "Xoá"),
                    Leaf("operationsOverviewHome.export", "Xuất dữ liệu")),
                Group("operationsOverviewProcess", "Quy trình",
                    Leaf("operationsOverviewProcess.read", "Xem"),
                    Leaf("operationsOverviewProcess.create", "Thêm"),
                    Leaf("operationsOverviewProcess.update", "Sửa"),
                    Leaf("operationsOverviewProcess.delete", "Xoá"),
                    Leaf("operationsOverviewProcess.export", "Xuất dữ liệu")),
                Group("operationsOverviewTask", "Công việc",
                    Leaf("operationsOverviewTask.read", "Xem"),
                    Leaf("operationsOverviewTask.create", "Thêm"),
                    Leaf("operationsOverviewTask.update", "Sửa"),
                    Leaf("operationsOverviewTask.delete", "Xoá"),
                    Leaf("operationsOverviewTask.export", "Xuất dữ liệu")),
                Group("operationsOverviewReport", "Báo cáo",
                    Leaf("operationsOverviewReport.read", "Xem"),
                    Leaf("operationsOverviewReport.export", "Xuất dữ liệu")),
                Group("operationsOverviewDiagnosis", "Chẩn đoán chưa điều trị",
                    Leaf("operationsOverviewDiagnosis.read", "Xem"),
                    Leaf("operationsOverviewDiagnosis.export", "Xuất dữ liệu")),
                Group("operationsOverviewPrescription", "Đơn thuốc",
                    Leaf("operationsOverviewPrescription.read", "Xem"),
                    Leaf("operationsOverviewPrescription.export", "Xuất dữ liệu"))),
            Group("operations-assistant", "Khối trợ lý",
                Group("operationsAssistantHome", "Trang chủ",
                    Leaf("operationsAssistantHome.read", "Xem"),
                    Leaf("operationsAssistantHome.create", "Thêm"),
                    Leaf("operationsAssistantHome.update", "Sửa"),
                    Leaf("operationsAssistantHome.delete", "Xoá"),
                    Leaf("operationsAssistantHome.export", "Xuất dữ liệu")),
                Group("operationsAssistantProcess", "Quy trình",
                    Leaf("operationsAssistantProcess.read", "Xem"),
                    Leaf("operationsAssistantProcess.create", "Thêm"),
                    Leaf("operationsAssistantProcess.update", "Sửa"),
                    Leaf("operationsAssistantProcess.delete", "Xoá"),
                    Leaf("operationsAssistantProcess.export", "Xuất dữ liệu")),
                Group("operationsAssistantTask", "Công việc",
                    Leaf("operationsAssistantTask.read", "Xem"),
                    Leaf("operationsAssistantTask.create", "Thêm"),
                    Leaf("operationsAssistantTask.update", "Sửa"),
                    Leaf("operationsAssistantTask.delete", "Xoá"),
                    Leaf("operationsAssistantTask.export", "Xuất dữ liệu"))),
            Group("operations-reception", "Khối lễ tân",
                Group("operationsReceptionHome", "Trang chủ",
                    Leaf("operationsReceptionHome.read", "Xem"),
                    Leaf("operationsReceptionHome.create", "Thêm"),
                    Leaf("operationsReceptionHome.update", "Sửa"),
                    Leaf("operationsReceptionHome.delete", "Xoá"),
                    Leaf("operationsReceptionHome.export", "Xuất dữ liệu")),
                Group("operationsReceptionProcess", "Quy trình",
                    Leaf("operationsReceptionProcess.read", "Xem"),
                    Leaf("operationsReceptionProcess.create", "Thêm"),
                    Leaf("operationsReceptionProcess.update", "Sửa"),
                    Leaf("operationsReceptionProcess.delete", "Xoá"),
                    Leaf("operationsReceptionProcess.export", "Xuất dữ liệu")),
                Group("operationsReceptionTask", "Công việc",
                    Leaf("operationsReceptionTask.read", "Xem"),
                    Leaf("operationsReceptionTask.create", "Thêm"),
                    Leaf("operationsReceptionTask.update", "Sửa"),
                    Leaf("operationsReceptionTask.delete", "Xoá"),
                    Leaf("operationsReceptionTask.export", "Xuất dữ liệu")),
                Group("operationsReceptionReport", "Báo cáo",
                    Leaf("operationsReceptionReport.read", "Xem"),
                    Leaf("operationsReceptionReport.export", "Xuất dữ liệu"))),
            Group("operations-cskh", "Khối CSKH",
                Group("operationsCskhHome", "Trang chủ",
                    Leaf("operationsCskhHome.read", "Xem"),
                    Leaf("operationsCskhHome.create", "Thêm"),
                    Leaf("operationsCskhHome.update", "Sửa"),
                    Leaf("operationsCskhHome.delete", "Xoá"),
                    Leaf("operationsCskhHome.export", "Xuất dữ liệu")),
                Group("operationsCskhProcess", "Quy trình",
                    Leaf("operationsCskhProcess.read", "Xem"),
                    Leaf("operationsCskhProcess.create", "Thêm"),
                    Leaf("operationsCskhProcess.update", "Sửa"),
                    Leaf("operationsCskhProcess.delete", "Xoá"),
                    Leaf("operationsCskhProcess.export", "Xuất dữ liệu")),
                Group("operationsCskhTask", "Công việc",
                    Leaf("operationsCskhTask.read", "Xem"),
                    Leaf("operationsCskhTask.create", "Thêm"),
                    Leaf("operationsCskhTask.update", "Sửa"),
                    Leaf("operationsCskhTask.delete", "Xoá"),
                    Leaf("operationsCskhTask.export", "Xuất dữ liệu")),
                Group("operationsCskhReport", "Báo cáo",
                    Leaf("operationsCskhReport.read", "Xem"),
                    Leaf("operationsCskhReport.export", "Xuất dữ liệu"))),
            Group("operations-marketing", "Khối Marketing",
                Group("operationsMarketingHome", "Trang chủ",
                    Leaf("operationsMarketingHome.read", "Xem"),
                    Leaf("operationsMarketingHome.create", "Thêm"),
                    Leaf("operationsMarketingHome.update", "Sửa"),
                    Leaf("operationsMarketingHome.delete", "Xoá"),
                    Leaf("operationsMarketingHome.export", "Xuất dữ liệu")),
                Group("operationsMarketingProcess", "Quy trình",
                    Leaf("operationsMarketingProcess.read", "Xem"),
                    Leaf("operationsMarketingProcess.create", "Thêm"),
                    Leaf("operationsMarketingProcess.update", "Sửa"),
                    Leaf("operationsMarketingProcess.delete", "Xoá"),
                    Leaf("operationsMarketingProcess.export", "Xuất dữ liệu")),
                Group("operationsMarketingTask", "Công việc",
                    Leaf("operationsMarketingTask.read", "Xem"),
                    Leaf("operationsMarketingTask.create", "Thêm"),
                    Leaf("operationsMarketingTask.update", "Sửa"),
                    Leaf("operationsMarketingTask.delete", "Xoá"),
                    Leaf("operationsMarketingTask.export", "Xuất dữ liệu")),
                Group("operationsMarketingReport", "Báo cáo",
                    Leaf("operationsMarketingReport.read", "Xem"),
                    Leaf("operationsMarketingReport.export", "Xuất dữ liệu"))),
            Group("operations-security", "Khối bảo vệ",
                Group("operationsSecurityHome", "Trang chủ",
                    Leaf("operationsSecurityHome.read", "Xem"),
                    Leaf("operationsSecurityHome.create", "Thêm"),
                    Leaf("operationsSecurityHome.update", "Sửa"),
                    Leaf("operationsSecurityHome.delete", "Xoá"),
                    Leaf("operationsSecurityHome.export", "Xuất dữ liệu")),
                Group("operationsSecurityProcess", "Quy trình",
                    Leaf("operationsSecurityProcess.read", "Xem"),
                    Leaf("operationsSecurityProcess.create", "Thêm"),
                    Leaf("operationsSecurityProcess.update", "Sửa"),
                    Leaf("operationsSecurityProcess.delete", "Xoá"),
                    Leaf("operationsSecurityProcess.export", "Xuất dữ liệu")),
                Group("operationsSecurityTask", "Công việc",
                    Leaf("operationsSecurityTask.read", "Xem"),
                    Leaf("operationsSecurityTask.create", "Thêm"),
                    Leaf("operationsSecurityTask.update", "Sửa"),
                    Leaf("operationsSecurityTask.delete", "Xoá"),
                    Leaf("operationsSecurityTask.export", "Xuất dữ liệu"))),
            Group("operations-treatment", "Khối điều trị",
                Group("operations-treatment-overview", "Tổng quan",
                    Group("operationsTreatmentHome", "Trang chủ",
                        Leaf("operationsTreatmentHome.read", "Xem"),
                        Leaf("operationsTreatmentHome.create", "Thêm"),
                        Leaf("operationsTreatmentHome.update", "Sửa"),
                        Leaf("operationsTreatmentHome.delete", "Xoá"),
                        Leaf("operationsTreatmentHome.export", "Xuất dữ liệu")),
                    Group("operationsTreatmentProcess", "Quy trình",
                        Leaf("operationsTreatmentProcess.read", "Xem"),
                        Leaf("operationsTreatmentProcess.create", "Thêm"),
                        Leaf("operationsTreatmentProcess.update", "Sửa"),
                        Leaf("operationsTreatmentProcess.delete", "Xoá"),
                        Leaf("operationsTreatmentProcess.export", "Xuất dữ liệu")),
                    Group("operationsTreatmentTask", "Công việc",
                        Leaf("operationsTreatmentTask.read", "Xem"),
                        Leaf("operationsTreatmentTask.create", "Thêm"),
                        Leaf("operationsTreatmentTask.update", "Sửa"),
                        Leaf("operationsTreatmentTask.delete", "Xoá"),
                        Leaf("operationsTreatmentTask.export", "Xuất dữ liệu")),
                    Group("operationsTreatmentReport", "Báo cáo",
                        Leaf("operationsTreatmentReport.read", "Xem"),
                        Leaf("operationsTreatmentReport.export", "Xuất dữ liệu"))),
                Group("operationsTreatmentAccess", "Truy cập",
                    Leaf("operationsTreatmentAccess.read", "Xem"),
                    Leaf("operationsTreatmentAccess.export", "Xuất dữ liệu"))),
            Group("operations-finance", "Khối tài chính",
                Group("operations-finance-overview", "Tổng quan",
                    Group("operationsFinanceHome", "Trang chủ",
                        Leaf("operationsFinanceHome.read", "Xem"),
                        Leaf("operationsFinanceHome.create", "Thêm"),
                        Leaf("operationsFinanceHome.update", "Sửa"),
                        Leaf("operationsFinanceHome.delete", "Xoá"),
                        Leaf("operationsFinanceHome.export", "Xuất dữ liệu")),
                    Group("operationsFinanceProcess", "Quy trình",
                        Leaf("operationsFinanceProcess.read", "Xem"),
                        Leaf("operationsFinanceProcess.create", "Thêm"),
                        Leaf("operationsFinanceProcess.update", "Sửa"),
                        Leaf("operationsFinanceProcess.delete", "Xoá"),
                        Leaf("operationsFinanceProcess.export", "Xuất dữ liệu")),
                    Group("operationsFinanceTask", "Công việc",
                        Leaf("operationsFinanceTask.read", "Xem"),
                        Leaf("operationsFinanceTask.create", "Thêm"),
                        Leaf("operationsFinanceTask.update", "Sửa"),
                        Leaf("operationsFinanceTask.delete", "Xoá"),
                        Leaf("operationsFinanceTask.export", "Xuất dữ liệu")),
                    Group("operationsFinanceInvoice", "Hóa đơn",
                        Leaf("operationsFinanceInvoice.read", "Xem"),
                        Leaf("operationsFinanceInvoice.export", "Xuất dữ liệu")),
                    Group("operationsFinanceServiceComplete", "Hoàn thành theo dịch vụ",
                        Leaf("operationsFinanceServiceComplete.read", "Xem"),
                        Leaf("operationsFinanceServiceComplete.export", "Xuất dữ liệu"))),
                Group("operationsFinanceAccess", "Truy cập",
                    Leaf("operationsFinanceAccess.read", "Xem"),
                    Leaf("operationsFinanceAccess.export", "Xuất dữ liệu")))),

        Group("labo-group", "Labo",
            Group("laboTemplate", "Mẫu labo",
                Leaf("laboTemplate.read", "Xem"),
                Leaf("laboTemplate.create", "Thêm"),
                Leaf("laboTemplate.update", "Sửa"),
                Leaf("laboTemplate.export", "Xuất dữ liệu")),
            Group("laboSupplier", "Nhà cung cấp Labo",
                Leaf("laboSupplier.read", "Xem"),
                Leaf("laboSupplier.create", "Thêm"),
                Leaf("laboSupplier.update", "Sửa"),
                Leaf("laboSupplier.delete", "Xoá"),
                Leaf("laboSupplier.export", "Xuất dữ liệu")),
            Group("laboBite", "Khớp cắn Labo",
                Leaf("laboBite.read", "Xem"),
                Leaf("laboBite.create", "Thêm"),
                Leaf("laboBite.update", "Sửa"),
                Leaf("laboBite.delete", "Xoá"),
                Leaf("laboBite.export", "Xuất dữ liệu")),
            Group("laboFinishLine", "Đường hoàn tất",
                Leaf("laboFinishLine.read", "Xem"),
                Leaf("laboFinishLine.create", "Thêm"),
                Leaf("laboFinishLine.update", "Sửa"),
                Leaf("laboFinishLine.delete", "Xoá"),
                Leaf("laboFinishLine.export", "Xuất dữ liệu")),
            Group("laboRhythm", "Kiểu nhịp Labo",
                Leaf("laboRhythm.read", "Xem"),
                Leaf("laboRhythm.create", "Thêm"),
                Leaf("laboRhythm.update", "Sửa"),
                Leaf("laboRhythm.delete", "Xoá"),
                Leaf("laboRhythm.export", "Xuất dữ liệu")),
            Group("laboMaterial", "Dịch vụ - vật liệu",
                Leaf("laboMaterial.read", "Xem"),
                Leaf("laboMaterial.create", "Thêm"),
                Leaf("laboMaterial.update", "Sửa"),
                Leaf("laboMaterial.delete", "Xoá"),
                Leaf("laboMaterial.export", "Xuất dữ liệu"))),

        Group("cskh-group", "Phân nhóm & CSKH",
            Group("cskhGroup", "Phân nhóm CSKH",
                Leaf("cskhGroup.read", "Xem"),
                Leaf("cskhGroup.create", "Thêm"),
                Leaf("cskhGroup.update", "Sửa"),
                Leaf("cskhGroup.export", "Xuất dữ liệu")),
            Group("cskhCare", "Chăm sóc khách hàng",
                Leaf("cskhCare.read", "Xem"),
                Leaf("cskhCare.create", "Thêm"),
                Leaf("cskhCare.update", "Sửa"),
                Leaf("cskhCare.export", "Xuất dữ liệu"))),

        Group("catalog-group", "Danh mục",
            Group("catalogPrescription", "Đơn thuốc mẫu",
                Leaf("catalogPrescription.read", "Xem"),
                Leaf("catalogPrescription.create", "Thêm"),
                Leaf("catalogPrescription.update", "Sửa"),
                Leaf("catalogPrescription.delete", "Xoá"),
                Leaf("catalogPrescription.export", "Xuất dữ liệu")),
            Group("catalogMedicine", "Loại thuốc",
                Leaf("catalogMedicine.read", "Xem"),
                Leaf("catalogMedicine.create", "Thêm"),
                Leaf("catalogMedicine.update", "Sửa"),
                Leaf("catalogMedicine.delete", "Xoá"),
                Leaf("catalogMedicine.export", "Xuất dữ liệu")),
            Group("catalogService", "Dịch vụ",
                Leaf("catalogService.read", "Xem"),
                Leaf("catalogService.create", "Thêm"),
                Leaf("catalogService.update", "Sửa"),
                Leaf("catalogService.delete", "Xoá"),
                Leaf("catalogService.export", "Xuất dữ liệu")),
            Group("catalogDiagnosis", "Chẩn đoán",
                Leaf("catalogDiagnosis.read", "Xem"),
                Leaf("catalogDiagnosis.create", "Thêm"),
                Leaf("catalogDiagnosis.update", "Sửa"),
                Leaf("catalogDiagnosis.delete", "Xoá"),
                Leaf("catalogDiagnosis.export", "Xuất dữ liệu")),
            Group("catalogConsultation", "Dữ liệu tư vấn",
                Leaf("catalogConsultation.read", "Xem"),
                Leaf("catalogConsultation.create", "Thêm"),
                Leaf("catalogConsultation.update", "Sửa"),
                Leaf("catalogConsultation.delete", "Xoá"),
                Leaf("catalogConsultation.export", "Xuất dữ liệu")),
            Group("catalogSource", "Nguồn đến",
                Leaf("catalogSource.read", "Xem"),
                Leaf("catalogSource.create", "Thêm"),
                Leaf("catalogSource.update", "Sửa"),
                Leaf("catalogSource.delete", "Xoá"),
                Leaf("catalogSource.export", "Xuất dữ liệu")),
            Group("catalogHistory", "Lịch sử bệnh",
                Leaf("catalogHistory.read", "Xem"),
                Leaf("catalogHistory.create", "Thêm"),
                Leaf("catalogHistory.update", "Sửa"),
                Leaf("catalogHistory.delete", "Xoá"),
                Leaf("catalogHistory.export", "Xuất dữ liệu")),
            Group("catalogTemplate", "Bệnh án mẫu",
                Leaf("catalogTemplate.read", "Xem"),
                Leaf("catalogTemplate.create", "Thêm"),
                Leaf("catalogTemplate.update", "Sửa"),
                Leaf("catalogTemplate.delete", "Xoá"),
                Leaf("catalogTemplate.export", "Xuất dữ liệu")),
            Group("catalogPost", "Bài viết / Tin tức",
                Leaf("catalogPost.read", "Xem"),
                Leaf("catalogPost.create", "Thêm"),
                Leaf("catalogPost.update", "Sửa"),
                Leaf("catalogPost.delete", "Xoá")),
            Group("catalogRecordTag", "Thẻ hồ sơ",
                Leaf("catalogRecordTag.read", "Xem"),
                Leaf("catalogRecordTag.create", "Thêm"),
                Leaf("catalogRecordTag.update", "Sửa"),
                Leaf("catalogRecordTag.delete", "Xoá")),
            Group("catalogPaymentMethod", "Phương thức thanh toán",
                Leaf("catalogPaymentMethod.read", "Xem"),
                Leaf("catalogPaymentMethod.create", "Thêm"),
                Leaf("catalogPaymentMethod.update", "Sửa"),
                Leaf("catalogPaymentMethod.delete", "Xoá")),
            Group("catalogOccupation", "Nghề nghiệp",
                Leaf("catalogOccupation.read", "Xem"),
                Leaf("catalogOccupation.create", "Thêm"),
                Leaf("catalogOccupation.update", "Sửa"),
                Leaf("catalogOccupation.delete", "Xoá"))),

        Group("report-group", "Báo cáo",
            Group("reportSales", "Doanh số và lượt khách",
                Leaf("reportSales.read", "Xem"),
                Leaf("reportSales.export", "Xuất dữ liệu")),
            Group("report-cashflow", "Quản lý thu chi",
                Group("reportIncome", "Thu nhập",
                    Leaf("reportIncome.read", "Xem"),
                    Leaf("reportIncome.create", "Thêm"),
                    Leaf("reportIncome.update", "Sửa"),
                    Leaf("reportIncome.delete", "Xoá"),
                    Leaf("reportIncome.export", "Xuất dữ liệu")),
                Group("reportCost", "Chi phí",
                    Leaf("reportCost.read", "Xem"),
                    Leaf("reportCost.create", "Thêm"),
                    Leaf("reportCost.update", "Sửa"),
                    Leaf("reportCost.delete", "Xoá"),
                    Leaf("reportCost.approve", "Duyệt chi"),
                    Leaf("reportCost.export", "Xuất dữ liệu")),
                Group("reportCashflowCategory", "Danh mục",
                    Leaf("reportCashflowCategory.read", "Xem"),
                    Leaf("reportCashflowCategory.create", "Thêm"),
                    Leaf("reportCashflowCategory.update", "Sửa"),
                    Leaf("reportCashflowCategory.delete", "Xoá"),
                    Leaf("reportCashflowCategory.export", "Xuất dữ liệu"))),
            Group("reportResult", "Kết quả kinh doanh",
                Leaf("reportResult.read", "Xem"),
                Leaf("reportResult.export", "Xuất dữ liệu")),
            Group("report-transfer-group", "Luân chuyển",
                Group("reportTransfer", "Tổng quan",
                    Leaf("reportTransfer.read", "Xem"),
                    Leaf("reportTransfer.update", "Sửa"),
                    Leaf("reportTransfer.delete", "Xoá"),
                    Leaf("reportTransfer.deposit", "Nạp"),
                    Leaf("reportTransfer.withdraw", "Rút"),
                    Leaf("reportTransfer.transfer", "Luân chuyển"),
                    Leaf("reportTransfer.export", "Xuất dữ liệu")),
                Group("reportTransferCategory", "Danh mục",
                    Leaf("reportTransferCategory.read", "Xem"),
                    Leaf("reportTransferCategory.create", "Thêm"),
                    Leaf("reportTransferCategory.update", "Sửa"),
                    Leaf("reportTransferCategory.delete", "Xoá")))),

        Group("materials", "Vật tư",
            Leaf("materials.read", "Xem"),
            Leaf("materials.create", "Thêm"),
            Leaf("materials.update", "Sửa"),
            Leaf("materials.delete", "Xoá"),
            Leaf("materials.approve", "Duyệt xác nhận số lượng"),
            Leaf("materials.export", "Xuất dữ liệu")),

        Group("staff", "Nhân viên",
            Leaf("staff.read", "Xem"),
            Leaf("staff.create", "Thêm"),
            Leaf("staff.update", "Sửa"),
            Leaf("staff.delete", "Xoá"),
            Leaf("staff.export", "Xuất dữ liệu")),

        Group("tools-group", "Công cụ",
            Group("toolCall", "Gọi thoại",
                Leaf("toolCall.read", "Xem"),
                Leaf("toolCall.create", "Thêm"),
                Leaf("toolCall.update", "Sửa"),
                Leaf("toolCall.delete", "Xoá"),
                Leaf("toolCall.export", "Xuất dữ liệu")),
            Group("toolMessage", "Tin nhắn",
                Leaf("toolMessage.read", "Xem"),
                Leaf("toolMessage.create", "Thêm"),
                Leaf("toolMessage.update", "Sửa"),
                Leaf("toolMessage.delete", "Xoá"),
                Leaf("toolMessage.export", "Xuất dữ liệu"))),

        Group("voucher", "Voucher khuyến mãi",
            Leaf("voucher.read", "Xem"),
            Leaf("voucher.create", "Thêm"),
            Leaf("voucher.update", "Sửa"),
            Leaf("voucher.delete", "Xoá"),
            Leaf("voucher.export", "Xuất dữ liệu")),

        Group("chatbot-group", "Trợ lý AI",
            Group("chatbot", "Tổng quan",
                Leaf("chatbot.read", "Xem"),
                Leaf("chatbot.create", "Thêm"),
                Leaf("chatbot.update", "Sửa"),
                Leaf("chatbot.delete", "Xoá"),
                Leaf("chatbot.approve", "Duyệt"),
                Leaf("chatbot.manage", "Quản lý toàn bộ")),
            Group("chatbotKnowledge", "Kho tri thức",
                Leaf("chatbotKnowledge.read", "Xem"),
                Leaf("chatbotKnowledge.create", "Thêm"),
                Leaf("chatbotKnowledge.update", "Sửa"),
                Leaf("chatbotKnowledge.delete", "Xoá"))),

        Group("account", "Tài khoản",
            Group("account-info", "Tài khoản",
                Leaf("account.read", "Xem"),
                Leaf("account.update", "Sửa")),
            Group("role-permission", "Phân quyền",
                Leaf("rolePermission.read", "Xem"),
                Leaf("rolePermission.create", "Thêm"),
                Leaf("rolePermission.update", "Sửa"),
                Leaf("rolePermission.delete", "Xoá"))),

        Group("helpSupport", "Hướng dẫn và hỗ trợ",
            Leaf("helpSupport.read", "Xem")),
    ];

    private static PermissionTreeNode Group(string id, string label, params PermissionTreeNode[] children) =>
        new() { Type = "group", Id = id, Label = label, Children = [..children] };

    private static PermissionTreeNode Leaf(string id, string label) =>
        new() { Type = "leaf", Id = id, Label = label };
}
