import { expect, test, type Download, type Page } from "@playwright/test";
import { assertRealApiTraffic, login, runId } from "./fixtures/auth";
import { pickOption, selectOption } from "./fixtures/antd";

/**
 * Feature: Xuất Excel / In PDF.
 *
 * Every one of these buttons used to be inert. The files are generated by the
 * server, so the test only passes if a real download arrives with real bytes.
 */
test.describe("Xuất file", () => {
  test.beforeEach(async ({ page }) => {
    await login(page);
  });

  /** Clicks a button and returns the file the browser received. */
  async function download(page: Page, name: string | RegExp): Promise<Download> {
    const [file] = await Promise.all([
      page.waitForEvent("download", { timeout: 30_000 }),
      page.getByRole("button", { name }).first().click(),
    ]);

    return file;
  }

  const sizeOf = async (file: Download): Promise<number> => {
    const path = await file.path();
    const { statSync } = await import("node:fs");
    return statSync(path).size;
  };

  test("the report tabs export a workbook", async ({ page }) => {
    await page.goto("/report");
    await assertRealApiTraffic(page, "/api/v1/app/clinic-reports/payment-stat");

    const sales = await download(page, "Xuất Excel");
    expect(sales.suggestedFilename()).toMatch(/doanh-so.*\.xlsx$/);
    expect(await sizeOf(sales)).toBeGreaterThan(1000);

    await page.goto("/report?tab=result");
    await assertRealApiTraffic(page, "/api/v1/app/clinic-reports/business-result");

    const result = await download(page, "Xuất Excel");
    expect(result.suggestedFilename()).toMatch(/ket-qua-kinh-doanh.*\.xlsx$/);
    expect(await sizeOf(result)).toBeGreaterThan(1000);
  });

  test("the patient list exports a workbook", async ({ page }) => {
    await page.goto("/patient");
    await assertRealApiTraffic(page, "/api/v1/app/patients");

    const file = await download(page, "Xuất file");
    expect(file.suggestedFilename()).toMatch(/benh-nhan.*\.xlsx$/);
    expect(await sizeOf(file)).toBeGreaterThan(1000);
  });

  test("a prescription prints as a PDF", async ({ page }) => {
    await page.goto("/patient");
    await assertRealApiTraffic(page, "/api/v1/app/patients");

    await page.locator("tr.ant-table-row").first().click();
    await page.getByRole("tab", { name: "Đơn thuốc" }).click();
    await assertRealApiTraffic(page, "/api/v1/app/prescriptions");

    // The test writes the slip it prints, so it never depends on leftover data.
    await page.getByRole("button", { name: "Tạo đơn thuốc" }).click();
    const dialog = page.getByRole("dialog");
    await selectOption(page, dialog, "Bác sĩ kê đơn");
    await dialog.getByLabel("Chẩn đoán", { exact: true }).fill(`In PDF ${runId()}`);
    await pickOption(page, dialog.getByTestId("prescription-medicine").getByRole("combobox"));
    await dialog.getByRole("button", { name: "Tạo", exact: true }).click();
    await expect(dialog).toBeHidden();

    const file = await download(page, "In đơn");
    expect(file.suggestedFilename()).toMatch(/^don-thuoc-.*\.pdf$/);

    // A PDF starts with %PDF; anything smaller than a kilobyte is not a document.
    const { readFileSync } = await import("node:fs");
    const bytes = readFileSync(await file.path());
    expect(bytes.subarray(0, 4).toString()).toBe("%PDF");
    expect(bytes.length).toBeGreaterThan(1000);
  });
});
