<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>BlueDental</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlueDental.Domain\BlueDental.Domain.csproj" />
    <ProjectReference Include="..\BlueDental.Application.Contracts\BlueDental.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.BlobStoring" Version="$(AbpVersion)" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
